default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: db/crucial_development

test:
  <<: *default
  database: db/crucial_test
  
staging:
  <<: *default
  database: db/crucial_production

production:
  <<: *default
  database: db/crucial_production
